project_id = "jctazmnlozmimjlrnfzq"

[api]
enabled = true

[functions.generate-3d]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
